version: '3.8'

services:
  # DockSafe Application
  docksafe-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///instance/docksafe_dev.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DOCSAFE_EMAIL_SMTP_SERVER=${DOCSAFE_EMAIL_SMTP_SERVER}
      - DOCSAFE_EMAIL_SMTP_PORT=${DOCSAFE_EMAIL_SMTP_PORT}
      - DOCSAFE_EMAIL_USERNAME=${DOCSAFE_EMAIL_USERNAME}
      - DOCSAFE_EMAIL_PASSWORD=${DOCSAFE_EMAIL_PASSWORD}
      - DOCSAFE_EMAIL_FROM=${DOCSAFE_EMAIL_FROM}
      - DOCSAFE_EMAIL_USE_TLS=${DOCSAFE_EMAIL_USE_TLS}
    volumes:
      - .:/app
      - docksafe-data:/app/instance
    depends_on:
      - redis
      - postgres
    networks:
      - docksafe-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=docksafe
      - POSTGRES_USER=docksafe
      - POSTGRES_PASSWORD=docksafe123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - docksafe-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - docksafe-network

  # Trivy Scanner Service
  trivy:
    image: aquasec/trivy:latest
    command: server --listen 0.0.0.0:4954
    ports:
      - "4954:4954"
    volumes:
      - trivy-cache:/root/.cache/trivy
    networks:
      - docksafe-network

  # Clair Scanner Service (Optional)
  clair:
    image: quay.io/coreos/clair:latest
    ports:
      - "6060:6060"
    volumes:
      - ./clair-config.yaml:/etc/clair/config.yaml
    networks:
      - docksafe-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - docksafe-app
    networks:
      - docksafe-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - docksafe-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - docksafe-network

volumes:
  docksafe-data:
  postgres-data:
  redis-data:
  trivy-cache:
  prometheus-data:
  grafana-data:

networks:
  docksafe-network:
    driver: bridge