"""Add NotificationConfiguration model

Revision ID: b10a25d38050
Revises: 
Create Date: 2025-10-12 10:56:06.295040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b10a25d38050"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_notification_history_group_id", "groups", ["group_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_history", schema=None) as batch_op:
        batch_op.drop_constraint("fk_notification_history_group_id", type_="foreignkey")
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
